services:
  db:
    build: 
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: database_parcial2
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./MySQL/volumes:/var/lib/mysql
    hostname: eam_database_parcial2
    networks:
      - net_parcial2
    healthcheck:
        test: ["CMD","mysql", "-u", "user", "-proot"]
        interval: 30s
        timeout: 5s
        retries: 5
# --------------------------------------------------------------------
  # - The adminer is a tool for managing content in databases.
  adminer:
    image: adminer
    container_name: adminer_parcial2
    restart: always
    ports:
      - 8080:8080
    networks:
      - net_parcial2
# --------------------------------------------------------------------
  # - fastapi refers to the container where the application backend will be stored.
  fastapi:
    build: 
      context: ./FastAPI
      dockerfile: Dockerfile
    container_name: backend_parcial2
    restart: always
    volumes:
      - ./FastAPI/app:/app 
    ports:
      - "8000:80"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80  # Recarga automática con --reload
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net_parcial2
# --------------------------------------------------------------------

networks:
  net_parcial2:
      driver: bridge
      name: net_parcial2