"""First COmmit - Alembic 

Revision ID: ad2c612a660c
Revises: 1566d9b9d860
Create Date: 2024-10-12 20:34:07.015633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2c612a660c'
down_revision: Union[str, None] = '1566d9b9d860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_account_type'), 'users', ['account_type'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_account_type'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
